insert into bank_address (id, details, state, zip_code, city, country) values (1, 'Room 1898', 'California', '90410', 'Santa Monica', 'United States');
insert into bank_address (id, details, state, zip_code, city, country) values (2, 'Apt 689', null, null, 'Pásion', 'Greece');
insert into bank_address (id, details, state, zip_code, city, country) values (3, 'Suite 51', null, null, 'Dashiju', 'China');
insert into bank_address (id, details, state, zip_code, city, country) values (4, '20th Floor', null, '379-2314', 'Ōmamachō-ōmama', 'Japan');
insert into bank_address (id, details, state, zip_code, city, country) values (5, 'PO Box 51885', 'Labuan', '87018', 'Labuan', 'Malaysia');
insert into bank_address (id, details, state, zip_code, city, country) values (6, 'PO Box 83899', null, null, 'Cukalat', 'Albania');
insert into bank_address (id, details, state, zip_code, city, country) values (7, 'Room 104', null, '63150-000', 'Campos Sales', 'Brazil');
insert into bank_address (id, details, state, zip_code, city, country) values (8, 'Suite 31', null, '6217', 'Ilihan', 'Philippines');
insert into bank_address (id, details, state, zip_code, city, country) values (9, 'Room 1951', null, null, 'Nūbā', 'Palestinian Territory');
insert into bank_address (id, details, state, zip_code, city, country) values (10, 'PO Box 66779', null, '95560-000', 'Torres', 'Brazil');
insert into bank_address (id, details, state, zip_code, city, country) values (11, 'Suite 28', null, null, 'Vovchans’k', 'Ukraine');
insert into bank_address (id, details, state, zip_code, city, country) values (12, 'Apt 718', null, null, 'Xinji', 'China');
insert into bank_address (id, details, state, zip_code, city, country) values (13, '3rd Floor', 'Aveiro', '3810-760', 'Póvoa do Valado', 'Portugal');
insert into bank_address (id, details, state, zip_code, city, country) values (14, 'Room 555', null, '838-0813', 'Yorii', 'Japan');
insert into bank_address (id, details, state, zip_code, city, country) values (15, 'Room 171', 'Porto', '4650-576', 'Barroco', 'Portugal');
insert into bank_address (id, details, state, zip_code, city, country) values (16, 'PO Box 29411', null, null, 'Cigadung', 'Indonesia');
insert into bank_address (id, details, state, zip_code, city, country) values (17, '11th Floor', null, '06400-000', 'Barueri', 'Brazil');
insert into bank_address (id, details, state, zip_code, city, country) values (18, '1st Floor', null, null, 'Cimuncang', 'Indonesia');
insert into bank_address (id, details, state, zip_code, city, country) values (19, 'PO Box 69753', null, null, 'Luojiaping', 'China');
insert into bank_address (id, details, state, zip_code, city, country) values (20, 'Apt 1685', null, null, 'Xiaohe', 'China');
insert into bank_address (id, details, state, zip_code, city, country) values (21, 'PO Box 42997', null, null, 'Diapaga', 'Burkina Faso');
insert into bank_address (id, details, state, zip_code, city, country) values (22, 'Suite 84', null, null, 'Carumas', 'Peru');
insert into bank_address (id, details, state, zip_code, city, country) values (23, 'Suite 44', null, null, 'Shetangpo', 'China');
insert into bank_address (id, details, state, zip_code, city, country) values (24, 'Apt 502', null, null, 'Rongdoi', 'China');
insert into bank_address (id, details, state, zip_code, city, country) values (25, '15th Floor', null, '9200', 'Esquel', 'Argentina');
insert into bank_address (id, details, state, zip_code, city, country) values (26, 'PO Box 97615', null, null, 'Gornje Živinice', 'Bosnia and Herzegovina');
insert into bank_address (id, details, state, zip_code, city, country) values (27, 'Room 1080', null, null, 'Dugu', 'China');
insert into bank_address (id, details, state, zip_code, city, country) values (28, 'Suite 22', null, null, 'Runaway Bay', 'Jamaica');
insert into bank_address (id, details, state, zip_code, city, country) values (29, 'Room 1771', null, '3363', 'Colonia Aurora', 'Argentina');
insert into bank_address (id, details, state, zip_code, city, country) values (30, 'Apt 1794', null, '463-0056', 'Shinshiro', 'Japan');
insert into bank_address (id, details, state, zip_code, city, country) values (31, '15th Floor', null, null, 'Atarodangwautu', 'Indonesia');
insert into bank_address (id, details, state, zip_code, city, country) values (32, 'Apt 402', 'Saskatchewan', 'B3H', 'Melfort', 'Canada');
insert into bank_address (id, details, state, zip_code, city, country) values (33, 'Suite 9', null, '673613', 'Vershino-Shakhtaminskiy', 'Russia');
insert into bank_address (id, details, state, zip_code, city, country) values (34, 'Apt 930', null, '69940-000', 'Sena Madureira', 'Brazil');
insert into bank_address (id, details, state, zip_code, city, country) values (35, 'Room 1155', null, null, 'Banjar Beratan', 'Indonesia');
insert into bank_address (id, details, state, zip_code, city, country) values (36, 'PO Box 33070', null, null, 'Zouma', 'China');
insert into bank_address (id, details, state, zip_code, city, country) values (37, 'Suite 64', null, 'MD-6214', 'Bilicenii Vechi', 'Moldova');
insert into bank_address (id, details, state, zip_code, city, country) values (38, 'PO Box 18964', null, null, 'Cipicung', 'Indonesia');
insert into bank_address (id, details, state, zip_code, city, country) values (39, 'Apt 1250', null, null, 'Dalam', 'Indonesia');
insert into bank_address (id, details, state, zip_code, city, country) values (40, '14th Floor', null, '6227', 'San Juan', 'Philippines');
insert into bank_address (id, details, state, zip_code, city, country) values (41, '13th Floor', null, '13660-000', 'Porto Ferreira', 'Brazil');
insert into bank_address (id, details, state, zip_code, city, country) values (42, 'PO Box 30819', null, null, 'Krajan', 'Indonesia');
insert into bank_address (id, details, state, zip_code, city, country) values (43, 'Suite 22', null, '184621', 'Safonovo', 'Russia');
insert into bank_address (id, details, state, zip_code, city, country) values (44, '10th Floor', null, null, 'Loncoche', 'Chile');
insert into bank_address (id, details, state, zip_code, city, country) values (45, 'Suite 39', null, null, 'Adzopé', 'Ivory Coast');
insert into bank_address (id, details, state, zip_code, city, country) values (46, 'Suite 74', null, '1773', 'Sanghan', 'Philippines');
insert into bank_address (id, details, state, zip_code, city, country) values (47, '11th Floor', null, '29051', 'Shorko', 'Pakistan');
insert into bank_address (id, details, state, zip_code, city, country) values (48, 'Room 90', null, '694902', 'Uglegorsk', 'Russia');
insert into bank_address (id, details, state, zip_code, city, country) values (49, 'PO Box 88392', null, null, 'Uspenka', 'Ukraine');
insert into bank_address (id, details, state, zip_code, city, country) values (50, 'Room 319', null, null, 'Āqchah', 'Afghanistan');
insert into bank_address (id, details, state, zip_code, city, country) values (51, 'Suite 35', null, '13183-000', 'Hortolândia', 'Brazil');
insert into bank_address (id, details, state, zip_code, city, country) values (52, '8th Floor', null, null, 'Miras', 'Albania');
insert into bank_address (id, details, state, zip_code, city, country) values (53, 'Room 921', null, null, 'Shenshan', 'China');
insert into bank_address (id, details, state, zip_code, city, country) values (54, 'Apt 1428', 'Coimbra', '3060-445', 'Ourentã', 'Portugal');
insert into bank_address (id, details, state, zip_code, city, country) values (55, 'Room 1017', null, null, 'Zumiao', 'China');
insert into bank_address (id, details, state, zip_code, city, country) values (56, 'Apt 171', null, null, 'Masparrito', 'Venezuela');
insert into bank_address (id, details, state, zip_code, city, country) values (57, '13th Floor', null, null, 'Pančevo', 'Serbia');
insert into bank_address (id, details, state, zip_code, city, country) values (58, 'PO Box 42110', null, null, 'Banjar Desa', 'Indonesia');
insert into bank_address (id, details, state, zip_code, city, country) values (59, 'PO Box 41583', 'Centre', '41976 CEDEX 9', 'Blois', 'France');
insert into bank_address (id, details, state, zip_code, city, country) values (60, 'Room 1202', 'Île-de-France', '91265 CEDEX', 'Juvisy-sur-Orge', 'France');
insert into bank_address (id, details, state, zip_code, city, country) values (61, 'Suite 66', 'Örebro', '694 24', 'Hallsberg', 'Sweden');
insert into bank_address (id, details, state, zip_code, city, country) values (62, 'Suite 97', null, null, 'Cuenca', 'Ecuador');
insert into bank_address (id, details, state, zip_code, city, country) values (63, 'Room 881', null, '377-0816', 'Nakanojōmachi', 'Japan');
insert into bank_address (id, details, state, zip_code, city, country) values (64, 'Apt 944', null, null, 'Changtang', 'China');
insert into bank_address (id, details, state, zip_code, city, country) values (65, 'Apt 626', null, null, 'Bắc Ninh', 'Vietnam');
insert into bank_address (id, details, state, zip_code, city, country) values (66, 'Apt 1624', null, null, 'Liulin', 'China');
insert into bank_address (id, details, state, zip_code, city, country) values (67, '16th Floor', null, null, 'Minian', 'Indonesia');
insert into bank_address (id, details, state, zip_code, city, country) values (68, '4th Floor', 'Campania', '84135', 'Salerno', 'Italy');
insert into bank_address (id, details, state, zip_code, city, country) values (69, 'Room 106', null, null, 'Kalyny', 'Ukraine');
insert into bank_address (id, details, state, zip_code, city, country) values (70, 'Apt 893', null, '10801', 'Guadalupe', 'Costa Rica');
insert into bank_address (id, details, state, zip_code, city, country) values (71, 'Suite 55', null, '11009', 'El Asintal', 'Guatemala');
insert into bank_address (id, details, state, zip_code, city, country) values (72, 'Room 660', null, null, 'Kolbano', 'Indonesia');
insert into bank_address (id, details, state, zip_code, city, country) values (73, 'PO Box 7049', null, '13110', 'Sena', 'Thailand');
insert into bank_address (id, details, state, zip_code, city, country) values (74, '13th Floor', 'Leiria', '2425-507', 'Várzeas', 'Portugal');
insert into bank_address (id, details, state, zip_code, city, country) values (75, 'Suite 32', null, null, 'Lincheng', 'China');
insert into bank_address (id, details, state, zip_code, city, country) values (76, 'Suite 3', null, null, 'Kandete', 'Tanzania');
insert into bank_address (id, details, state, zip_code, city, country) values (77, 'Room 1066', 'Rhône-Alpes', '69519 CEDEX', 'Vaulx-en-Velin', 'France');
insert into bank_address (id, details, state, zip_code, city, country) values (78, 'PO Box 75771', null, '353673', 'Yasenskaya', 'Russia');
insert into bank_address (id, details, state, zip_code, city, country) values (79, '19th Floor', null, null, 'Mairana', 'Bolivia');
insert into bank_address (id, details, state, zip_code, city, country) values (80, '5th Floor', 'Santarém', '6120-625', 'Penhascoso', 'Portugal');
insert into bank_address (id, details, state, zip_code, city, country) values (81, 'PO Box 48827', 'Chiapas', '30560', 'San Miguel', 'Mexico');
insert into bank_address (id, details, state, zip_code, city, country) values (82, '9th Floor', null, null, 'Temirtau', 'Kazakhstan');
insert into bank_address (id, details, state, zip_code, city, country) values (83, 'PO Box 35314', null, '11305', 'Colima', 'Costa Rica');
insert into bank_address (id, details, state, zip_code, city, country) values (84, 'Room 623', null, '62-050', 'Mosina', 'Poland');
insert into bank_address (id, details, state, zip_code, city, country) values (85, 'Suite 48', null, null, 'Parapat', 'Indonesia');
insert into bank_address (id, details, state, zip_code, city, country) values (86, 'Apt 370', null, null, 'Tawa', 'China');
insert into bank_address (id, details, state, zip_code, city, country) values (87, 'Room 1533', null, null, 'Leicheng', 'China');
insert into bank_address (id, details, state, zip_code, city, country) values (88, '4th Floor', 'Ontario', 'V5M', 'Mattawa', 'Canada');
insert into bank_address (id, details, state, zip_code, city, country) values (89, 'Apt 1060', null, null, 'Triandría', 'Greece');
insert into bank_address (id, details, state, zip_code, city, country) values (90, 'Apt 679', null, 'P61', 'Fermoy', 'Ireland');
insert into bank_address (id, details, state, zip_code, city, country) values (91, '20th Floor', 'Coimbra', '3070-085', 'Cential', 'Portugal');
insert into bank_address (id, details, state, zip_code, city, country) values (92, 'Suite 43', 'Västra Götaland', '433 84', 'Partille', 'Sweden');
insert into bank_address (id, details, state, zip_code, city, country) values (93, 'Suite 58', 'Auvergne', '03104 CEDEX', 'Montluçon', 'France');
insert into bank_address (id, details, state, zip_code, city, country) values (94, 'Apt 528', null, null, 'Shangyuan', 'China');
insert into bank_address (id, details, state, zip_code, city, country) values (95, 'PO Box 84627', null, null, 'Paucarcolla', 'Peru');
insert into bank_address (id, details, state, zip_code, city, country) values (96, 'PO Box 25295', 'Sicilia', '98135', 'Messina', 'Italy');
insert into bank_address (id, details, state, zip_code, city, country) values (97, '8th Floor', null, '623036', 'Staroutkinsk', 'Russia');
insert into bank_address (id, details, state, zip_code, city, country) values (98, '11th Floor', null, null, 'Desa Gegempalan', 'Indonesia');
insert into bank_address (id, details, state, zip_code, city, country) values (99, 'Apt 65', 'Coimbra', '3140-253', 'Montemor-o-Velho', 'Portugal');
insert into bank_address (id, details, state, zip_code, city, country) values (100, 'Apt 392', null, '24120', 'Chanthaburi', 'Thailand');
