# Generated by Django 4.2.5 on 2023-09-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='name',
        ),
        migrations.AddField(
            model_name='branch',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
